use_frameworks!

platform :ios, '13.0'

target 'videoFK_Example' do
  pod 'videoFK', :path => '../'

  use_frameworks!

  
  pod 'QMUIKit', '4.6.1'
  pod 'Masonry'
  pod 'HYBaseTool', '1.0.4'
  pod 'AFNetworking'
  pod 'CTNetworking'
  pod 'JXCategoryView'
  pod 'YYModel'
  pod 'HYText'
  pod 'YYCategories'
  pod 'YYWebImage'
  pod 'MJRefresh'
  pod 'WCDB.swift', '1.1.0'
  pod 'Alamofire', '4.9.1'
  pod 'HandyJSON', '5.0.2'
  pod 'SnapKit', '5.6.0'
  
  post_install do |pi|
    
    xcode_base_version = `xcodebuild -version | grep 'Xcode' | awk '{print $2}' | cut -d . -f 1`
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
          xcconfig_path = config.base_configuration_reference.real_path
          xcconfig = File.read(xcconfig_path)
          xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
          File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
        
      end
    end
  end
  
  target 'videoFK_Tests' do
    inherit! :search_paths

    
  end
end
